# Generated by Django 5.1.7 on 2025-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total')),
                ('estado', models.CharField(default='pendiente', max_length=20, verbose_name='Estado Actual')),
            ],
        ),
    ]
