# Generated by Django 5.1.7 on 2025-03-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(max_length=300, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado Actual'),
        ),
    ]
