# Generated by Django 5.1.7 on 2025-05-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
